// Test IDs for the home / landing page.
export const HOME = {
    emergentLink: 'home-emergent-link',
    nav: 'home-nav',
    navLogo: 'home-nav-logo',
    ctaConsultation: 'home-cta-consultation',
    ctaPrograms: 'home-cta-programs',
    heroSection: 'home-hero',
    aboutSection: 'home-about',
    impactSection: 'home-impact',
    programsSection: 'home-programs',
    journeySection: 'home-journey',
    alphaSonicSection: 'home-alpha-sonic',
    teamSection: 'home-team',
    franchiseSection: 'home-franchise',
    testimonialsSection: 'home-testimonials',
    gallerySection: 'home-gallery',
    faqSection: 'home-faq',
    contactSection: 'home-contact',
    contactForm: 'home-contact-form',
    contactName: 'home-contact-name',
    contactEmail: 'home-contact-email',
    contactPhone: 'home-contact-phone',
    contactAge: 'home-contact-age',
    contactMessage: 'home-contact-message',
    contactSubmit: 'home-contact-submit',
    franchiseRsvp: 'home-franchise-rsvp',
    womenEmpowermentSection: 'home-women-empowerment',
    presenceSection: 'home-presence',
    franchiseEnquirySection: 'home-franchise-enquiry',
    franchiseEnquiryForm: 'home-franchise-enquiry-form',
    franchiseEnquirySubmit: 'home-franchise-enquiry-submit',
};
